# (C) 2026: Hans Georg Schaathun <georg@schaathun.net> 
[simulator]
config = [ "raysie" ]
size = 20000
nterms = 4
imagesize = 512
cropsize = 256
centred = true

[dataset]
directory = "images"

[lens]
# Einstein radius 0.1" .. 3.0"
einstein-min = 2.5
einstein-max = 75
# orientation and ellipseratio are used for SIE lenses
orientation-min = 0
orientation-max = 180
ellipseratio-min = 0.1
ellipseratio-max = 0.9

[source]
mode = "SersicSphere"
n_sersic-min = 1
n_sersic-max = 5
luminosity-min = 10
luminosity-max = 20
luminosity-lambda = 2.0
# sigma (source size) 0.04"..0.2"
sigma-min = 1
sigma-max = 5
position = "relative"

[position]
# (phi,r) is the source position in polar co-ordinates, angle in degrees
phi-min = 0
phi-max = 360
r-relativemax = 1.2
