# (C) 2026: Hans Georg Schaathun <georg@schaathun.net> 
# This configures training of a machine learning model for CosmoAI
[settings]
device = "cuda"
models = [ "regnet_y_32gf" ]
problem = "problem.toml"

[hyperparameters.array]
learning-rate = [ 1e-3 ]
batch-size = [ 32 ]
weight-decay = [ 1e-4 ]

[training]
num-epochs = 50
patience = 10

[dataset]
directory = "images"
training.filename = "training.csv"
testing.filename = "testing.csv"
validation.filename = "validation.csv"

[output]
dirbase = "experiment%%"
# Predictions are placed in the output directory using the
# same filenames as the input files (training/testing/validation).
