[problem]
filename = "sie-roulette.csv"
dataset =  "sie-dataset.toml"
variables = [ "sigma", "sigma2", "theta", "xiX", "xiY" ]
nterms = 4 

[dataset]
roulette = "resimulation"

[dataset.training]
filename = "sie-training.csv"
predictionfile = "pred-sie-training.csv"
size = 10000

[dataset.validation]
filename = "sie-validation.csv"
predictionfile = "pred-sie-validation.csv"
size = 1000

[dataset.testing]
filename = "sie-testing.csv"
predictionfile = "pred-sie-testing.csv"
size = 4000
