# (C) 2026: Hans Georg Schaathun <georg@schaathun.net> 
[simulator]
model = "Raytrace"
size = 15000
nterms = 4
imagesize = 512
cropsize = 256
centred = true

[dataset]
directory = "images"

[lens]
mode = "SIE"
# Einstein radius 0.1" .. 3.0"
einstein-min = 3
einstein-max = 75
# orientation and ellipseratio are used for SIE lenses
orientation-min = 0
orientation-max = 180
ellipseratio-min = 0.1
ellipseratio-max = 0.9

[cluster]
count = 2
maxrelativelocation = 1.2

[source]
mode = "SersicSphere"
n_sersic-min = 1
n_sersic-max = 5
luminosity-min = 20
luminosity-max = 80
luminosity-lambda = 2.0
# sigma (source size) 0.04"..0.2"
sigma-min = 5
sigma-max = 50
position = "critical"

[position]
# (phi,r) is the source position in polar co-ordinates, angle in degrees
phi-min = 0
phi-max = 360
r-relativemax = 1.2
